### PR TITLE
Home page update, major overhaul of styling to follow google material design guide

### PR DESCRIPTION
**Pull request by johnhof**
@DuaneGarber  this is almost entirely aesthetic. 

I update the layout and structure to follow the [google material design guide](http://www.google.com/design/spec/material-design/introduction.html)

~~I'll make a README PR soon to explain everything, and how FE/styling will be structured. the colors are easy to change with this implementation (so dont worry if you  dont like the color palate).~~ updated. see readme for details

I laid out the skeleton for the home page. I didnt get much further because functionality requires a populated datase, which we dont have

### CODE REVIEW

**Comment by johnhof** [comment]
I accounted for edge cases, so update the controller data model if you want to see how no results/too many results are handled

**Comment by DuaneGarber** [comment]
@johnhof I cant get my server to start ... I'll dig in, on a side note, it looks like our travis builds are failing to start the server cause the test suite shows the same errors when the server isnt running

**Comment by johnhof** [comment]
@DuaneGarber I cleaned and re npm/bower installed and everything is dandy. could you post the stack trace?

ya, I assumed the server wasn't starting `ECONNREFUSED` is being thrown on every request the test makes, and I dont see the start script being run in the log. I'll discuss more in the other PR

**Comment by DuaneGarber** [comment]
Looks Purty

**Pull request merged**
