### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by johnhof**
@DuaneGarber

### CODE REVIEW

**Comment by johnhof** [comment]
@DuaneGarber do you have access to the travis builds since youre a contributor? https://travis-ci.org/johnhof/IceBuddy/builds

**Comment by DuaneGarber** [comment]
@johnhof Yeah, I can see the builds

**Comment by DuaneGarber** [comment]
@johnhof Dunno why the builds are failing, but I couldnt reproduce on local matching test run ... so Im good to go here

**Comment by johnhof** [comment]
looks like the servers not starting up anywhere in the build log. Ill look into it

**Pull request merged**
